version: '3.4'

services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: S3cur3P@ssW0rd!
            ACCEPT_EULA: Y
        volumes:
            - db-data:/var/lib/mssql/data

    shop-api:
        image: shop-api:${TAG:-latest}
        container_name: shop-api
        environment:
              - DefaultConnection=Server=db;Initial Catalog=ShopDb;TrustServerCertificate=true;User Id=sa;Password=S3cur3P@ssW0rd!
              - IdentityBaseAddress=http://identity-api
        build:
            context: .
            dockerfile: Shop.Api/Dockerfile
        ports:
            - 5000:80
        depends_on:
            - db
            - identity-api

    identity-api:
        image: shop-identity-api:${TAG:-latest}
        container_name: identity-api
        environment:
              - DefaultConnection=Server=db;Initial Catalog=IdentityDb;TrustServerCertificate=true;User Id=sa;Password=S3cur3P@ssW0rd!
        build:
            context: .
            dockerfile: Shop.IdentityApi/Dockerfile
        ports:
            - 5001:80
        depends_on:
            - db

volumes:
 db-data: